name = "GeoMet"
uuid = "17f98db7-af68-4c95-97fe-c6749748e69a"
authors = ["Geometallurgy Lab - UFMG"]
version = "0.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "1.0, 2.0"
DecisionTree = "0.12"
MultivariateStats = "0.10.3"
Statistics = "1.11.1"
julia = "1.6, 1.9, 1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
